name: example
description: Automatically generates immutable data classes for you based on a mutable "blueprint" class.
version: 1.0.0
author: Marcel Garus <marcel.garus@gmail.com>
homepage: https://github.com/marcelgarus/flutter_data_classes

dependencies:
  data_classes: ^3.0.0
  json_serializable: ^3.2.3

dev_dependencies:
  build_runner: ^1.7.1
  data_classes_generator: ^3.0.0
