name: data_classes
description: Automatically generates immutable data classes for you based on a mutable "blueprint" class.
version: 2.1.0
author: Marcel Garus <marcel.garus@gmail.com>
homepage: https://github.com/marcelgarus/data_classes

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  meta: ^1.1.7
